# Hacky secret project 3

trigger:
- main

pr:
- main

jobs:
- job: Build
  strategy:
    matrix:
      mac:
        imageName: 'macos-10.15'
        isMac: True

  steps:
  - checkout: self
    fetchDepth: 1
    # submodules: recursive # can't do submodules here b'cuz depth=1 fails with Github

  - bash: |
      echo "This repo is no longer used"
    displayName: Run CMake

